//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Animations/CatInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CatInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CatInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CatInputActions"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""7fcc92f0-640c-45da-be4a-75197d69c17e"",
            ""actions"": [
                {
                    ""name"": ""Newaction"",
                    ""type"": ""Value"",
                    ""id"": ""5f6842ec-2018-485a-971c-d56486eada46"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Move"",
                    ""id"": ""19a8ad5b-51eb-4f84-8f27-3b2a75561a30"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Newaction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""11bb9446-0dee-4a55-89c2-f2c31c31d2e7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Newaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""913fd9c1-8497-40af-9985-2d1eeba4a7b6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Newaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""28ca723f-13e7-41d7-be4a-62e5fe16c0d6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Newaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""97474af2-5ffb-4791-9c45-bdafe424d7e4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Newaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Jump"",
            ""id"": ""9462d987-8a79-42f8-90f8-233bdf6d7bb0"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""41931dee-f4e5-44e3-9d3f-b070f2eb0742"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f0bd918e-7610-4df0-bffb-5594f9b56d21"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Attack"",
            ""id"": ""c9417d3b-5178-4935-bfc6-13a3ef6d619f"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""05742517-bc2d-439e-b5f4-6eb64966a9d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""27657107-cd5d-4f9f-966d-2a0cdbca4ff3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FuryMode"",
            ""id"": ""6d817b66-affe-44e0-a258-d2394708cbfd"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""4eb13131-5928-4fc0-be3f-a60a6c6f3564"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0abcfc33-1955-4ee2-8e51-15b0c8a6f935"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Run"",
            ""id"": ""4966aee0-22a2-452c-ac2a-f2570b5ed356"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""ea84475a-71f5-4d74-9a85-bbe4e427c3b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd0bc611-80ec-4d70-851c-9a15237e2c62"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ToggleInventory"",
            ""id"": ""0a0b824c-1145-4e35-a207-edeb30090a07"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""9cbdf66b-924a-4297-8dda-3dd31abc69ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3d56894e-8798-43ea-8988-3200919743ae"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Map"",
            ""id"": ""b7e266f4-c8ae-4489-b73b-2079142fc9a2"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""af073245-8f21-4860-b41c-d32ed7b85f0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0f7fb8d1-5d79-4cd9-a627-aca22acdd31a"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Interact"",
            ""id"": ""6b8db64c-0655-4ca1-b138-f990c03d3153"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""52c15b99-8a06-4bf4-ab95-c16463dfa53d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3d2113a0-6c0c-4ad5-9da8-92b305c8ea50"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SaveGame"",
            ""id"": ""92dd71f9-430a-47c0-a906-24d9a6e32512"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""25881a0d-7a83-4578-bc28-8e8243b85633"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""af4c5207-ce89-4fca-974d-54ec78b31a1f"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dash"",
            ""id"": ""14f78116-1d54-4dc8-8a54-7bd3ab2bec64"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""9af91fe2-5698-487a-b9a0-41c32a4359e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4ed3902-8233-466d-874d-2dd064c1f0e1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Parry"",
            ""id"": ""c67b0888-125c-42cc-a9bb-93bcfe52a1bc"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""7b518537-a685-43ca-b0bb-55ddada9d607"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c33b8a87-825e-4600-a331-ca9aa2ba8a7a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Transformation"",
            ""id"": ""51d822c4-b386-4a4b-ae96-dd02d4a5e159"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""68565d0e-3552-48a8-9104-ea0afa71c139"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""79e63885-0c38-455b-9168-8447b63c01c6"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DrawWeapon"",
            ""id"": ""12df2672-c14e-4aa7-8732-0222bc17df32"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""111ef630-271d-46f0-949e-0c9da91c2fc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""53521608-41bf-4803-9350-71bbc6f3c390"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_Newaction = m_Move.FindAction("Newaction", throwIfNotFound: true);
        // Jump
        m_Jump = asset.FindActionMap("Jump", throwIfNotFound: true);
        m_Jump_Newaction = m_Jump.FindAction("New action", throwIfNotFound: true);
        // Attack
        m_Attack = asset.FindActionMap("Attack", throwIfNotFound: true);
        m_Attack_Newaction = m_Attack.FindAction("New action", throwIfNotFound: true);
        // FuryMode
        m_FuryMode = asset.FindActionMap("FuryMode", throwIfNotFound: true);
        m_FuryMode_Newaction = m_FuryMode.FindAction("New action", throwIfNotFound: true);
        // Run
        m_Run = asset.FindActionMap("Run", throwIfNotFound: true);
        m_Run_Newaction = m_Run.FindAction("New action", throwIfNotFound: true);
        // ToggleInventory
        m_ToggleInventory = asset.FindActionMap("ToggleInventory", throwIfNotFound: true);
        m_ToggleInventory_Newaction = m_ToggleInventory.FindAction("New action", throwIfNotFound: true);
        // Map
        m_Map = asset.FindActionMap("Map", throwIfNotFound: true);
        m_Map_Newaction = m_Map.FindAction("New action", throwIfNotFound: true);
        // Interact
        m_Interact = asset.FindActionMap("Interact", throwIfNotFound: true);
        m_Interact_Newaction = m_Interact.FindAction("New action", throwIfNotFound: true);
        // SaveGame
        m_SaveGame = asset.FindActionMap("SaveGame", throwIfNotFound: true);
        m_SaveGame_Newaction = m_SaveGame.FindAction("New action", throwIfNotFound: true);
        // Dash
        m_Dash = asset.FindActionMap("Dash", throwIfNotFound: true);
        m_Dash_Newaction = m_Dash.FindAction("New action", throwIfNotFound: true);
        // Parry
        m_Parry = asset.FindActionMap("Parry", throwIfNotFound: true);
        m_Parry_Newaction = m_Parry.FindAction("New action", throwIfNotFound: true);
        // Transformation
        m_Transformation = asset.FindActionMap("Transformation", throwIfNotFound: true);
        m_Transformation_Newaction = m_Transformation.FindAction("New action", throwIfNotFound: true);
        // DrawWeapon
        m_DrawWeapon = asset.FindActionMap("DrawWeapon", throwIfNotFound: true);
        m_DrawWeapon_Newaction = m_DrawWeapon.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_Newaction;
    public struct MoveActions
    {
        private @CatInputActions m_Wrapper;
        public MoveActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Move_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);

    // Jump
    private readonly InputActionMap m_Jump;
    private IJumpActions m_JumpActionsCallbackInterface;
    private readonly InputAction m_Jump_Newaction;
    public struct JumpActions
    {
        private @CatInputActions m_Wrapper;
        public JumpActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Jump_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Jump; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JumpActions set) { return set.Get(); }
        public void SetCallbacks(IJumpActions instance)
        {
            if (m_Wrapper.m_JumpActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_JumpActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_JumpActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_JumpActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_JumpActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public JumpActions @Jump => new JumpActions(this);

    // Attack
    private readonly InputActionMap m_Attack;
    private IAttackActions m_AttackActionsCallbackInterface;
    private readonly InputAction m_Attack_Newaction;
    public struct AttackActions
    {
        private @CatInputActions m_Wrapper;
        public AttackActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Attack_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Attack; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AttackActions set) { return set.Get(); }
        public void SetCallbacks(IAttackActions instance)
        {
            if (m_Wrapper.m_AttackActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_AttackActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_AttackActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_AttackActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_AttackActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public AttackActions @Attack => new AttackActions(this);

    // FuryMode
    private readonly InputActionMap m_FuryMode;
    private IFuryModeActions m_FuryModeActionsCallbackInterface;
    private readonly InputAction m_FuryMode_Newaction;
    public struct FuryModeActions
    {
        private @CatInputActions m_Wrapper;
        public FuryModeActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_FuryMode_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_FuryMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FuryModeActions set) { return set.Get(); }
        public void SetCallbacks(IFuryModeActions instance)
        {
            if (m_Wrapper.m_FuryModeActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_FuryModeActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_FuryModeActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_FuryModeActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_FuryModeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public FuryModeActions @FuryMode => new FuryModeActions(this);

    // Run
    private readonly InputActionMap m_Run;
    private IRunActions m_RunActionsCallbackInterface;
    private readonly InputAction m_Run_Newaction;
    public struct RunActions
    {
        private @CatInputActions m_Wrapper;
        public RunActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Run_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Run; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RunActions set) { return set.Get(); }
        public void SetCallbacks(IRunActions instance)
        {
            if (m_Wrapper.m_RunActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_RunActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_RunActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_RunActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_RunActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public RunActions @Run => new RunActions(this);

    // ToggleInventory
    private readonly InputActionMap m_ToggleInventory;
    private IToggleInventoryActions m_ToggleInventoryActionsCallbackInterface;
    private readonly InputAction m_ToggleInventory_Newaction;
    public struct ToggleInventoryActions
    {
        private @CatInputActions m_Wrapper;
        public ToggleInventoryActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_ToggleInventory_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_ToggleInventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ToggleInventoryActions set) { return set.Get(); }
        public void SetCallbacks(IToggleInventoryActions instance)
        {
            if (m_Wrapper.m_ToggleInventoryActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_ToggleInventoryActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_ToggleInventoryActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_ToggleInventoryActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_ToggleInventoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public ToggleInventoryActions @ToggleInventory => new ToggleInventoryActions(this);

    // Map
    private readonly InputActionMap m_Map;
    private IMapActions m_MapActionsCallbackInterface;
    private readonly InputAction m_Map_Newaction;
    public struct MapActions
    {
        private @CatInputActions m_Wrapper;
        public MapActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Map_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapActions set) { return set.Get(); }
        public void SetCallbacks(IMapActions instance)
        {
            if (m_Wrapper.m_MapActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_MapActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_MapActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_MapActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_MapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public MapActions @Map => new MapActions(this);

    // Interact
    private readonly InputActionMap m_Interact;
    private IInteractActions m_InteractActionsCallbackInterface;
    private readonly InputAction m_Interact_Newaction;
    public struct InteractActions
    {
        private @CatInputActions m_Wrapper;
        public InteractActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Interact_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Interact; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractActions set) { return set.Get(); }
        public void SetCallbacks(IInteractActions instance)
        {
            if (m_Wrapper.m_InteractActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_InteractActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_InteractActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_InteractActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_InteractActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public InteractActions @Interact => new InteractActions(this);

    // SaveGame
    private readonly InputActionMap m_SaveGame;
    private ISaveGameActions m_SaveGameActionsCallbackInterface;
    private readonly InputAction m_SaveGame_Newaction;
    public struct SaveGameActions
    {
        private @CatInputActions m_Wrapper;
        public SaveGameActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_SaveGame_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_SaveGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SaveGameActions set) { return set.Get(); }
        public void SetCallbacks(ISaveGameActions instance)
        {
            if (m_Wrapper.m_SaveGameActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_SaveGameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public SaveGameActions @SaveGame => new SaveGameActions(this);

    // Dash
    private readonly InputActionMap m_Dash;
    private IDashActions m_DashActionsCallbackInterface;
    private readonly InputAction m_Dash_Newaction;
    public struct DashActions
    {
        private @CatInputActions m_Wrapper;
        public DashActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Dash_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Dash; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DashActions set) { return set.Get(); }
        public void SetCallbacks(IDashActions instance)
        {
            if (m_Wrapper.m_DashActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_DashActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_DashActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_DashActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_DashActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public DashActions @Dash => new DashActions(this);

    // Parry
    private readonly InputActionMap m_Parry;
    private IParryActions m_ParryActionsCallbackInterface;
    private readonly InputAction m_Parry_Newaction;
    public struct ParryActions
    {
        private @CatInputActions m_Wrapper;
        public ParryActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Parry_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Parry; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ParryActions set) { return set.Get(); }
        public void SetCallbacks(IParryActions instance)
        {
            if (m_Wrapper.m_ParryActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_ParryActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_ParryActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_ParryActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_ParryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public ParryActions @Parry => new ParryActions(this);

    // Transformation
    private readonly InputActionMap m_Transformation;
    private ITransformationActions m_TransformationActionsCallbackInterface;
    private readonly InputAction m_Transformation_Newaction;
    public struct TransformationActions
    {
        private @CatInputActions m_Wrapper;
        public TransformationActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Transformation_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Transformation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TransformationActions set) { return set.Get(); }
        public void SetCallbacks(ITransformationActions instance)
        {
            if (m_Wrapper.m_TransformationActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_TransformationActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_TransformationActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_TransformationActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_TransformationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public TransformationActions @Transformation => new TransformationActions(this);

    // DrawWeapon
    private readonly InputActionMap m_DrawWeapon;
    private IDrawWeaponActions m_DrawWeaponActionsCallbackInterface;
    private readonly InputAction m_DrawWeapon_Newaction;
    public struct DrawWeaponActions
    {
        private @CatInputActions m_Wrapper;
        public DrawWeaponActions(@CatInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_DrawWeapon_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_DrawWeapon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DrawWeaponActions set) { return set.Get(); }
        public void SetCallbacks(IDrawWeaponActions instance)
        {
            if (m_Wrapper.m_DrawWeaponActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_DrawWeaponActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_DrawWeaponActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_DrawWeaponActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_DrawWeaponActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public DrawWeaponActions @DrawWeapon => new DrawWeaponActions(this);
    public interface IMoveActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IJumpActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IAttackActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IFuryModeActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IRunActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IToggleInventoryActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IMapActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IInteractActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface ISaveGameActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IDashActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IParryActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface ITransformationActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IDrawWeaponActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
